name: security-scan

on:
  push:
    branch:
      - main
  pull_request:
    branch:
       - main

jobs:
  git-leaks:
    name: security-scan
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: git-leaks
        uses: gitleaks/gitleaks-actions@v2
